version: '3.8'

services:
  mc:
    image: itzg/minecraft-server:latest
    volumes:
    - ./modpacks:/modpacks:ro
    - ./data:/data
    environment:
      EULA: "true"
      MEMORY: "1536M"
      ONLINE_MODE: "false"
      MAX_WORLD_SIZE: "25000"
    ports:
      - "25565:25565"

volumes:
  data: {}
