version: '3.8'

services:
  mc:
    image: itzg/minecraft-server:latest
    volumes:
    - ./modpacks:/modpacks:ro
    - ./data:/data
    environment:
      TYPE: BUKKIT
      BUKKIT_DOWNLOAD_URL: "https://drive.google.com/uc?export=download&confirm=no_antivirus&id=1wVGgKTVsgYwuLLwNGVmg-5_9SmPxsxPQ"
      EULA: "true"
      MEMORY: "3G"
      ONLINE_MODE: "false"
      MAX_WORLD_SIZE: "25000"
    ports:
      - "25565:25565"

volumes:
  data: {}
