version: '3.8'

services:
  mc:
    image: itzg/minecraft-server:latest
    volumes:
    - ./modpacks:/modpacks:ro
    - ./data:/data
    environment:
      EULA: "true"
      MEMORY: ""
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=75"
      MAX_MEMORY: "1G"
      INIT_MEMORY: "512M"
    ports:
      - "25565:25565"

volumes:
  data: {}
